import React from 'react';
import { 
  Tag, Wallet, TrendingUp, Briefcase, BarChart, Home, Gift, Utensils, Car, 
  ShoppingBag, Film, HeartPulse, Zap, Book, Plane, Shield, Settings,
  RefreshCw, ArrowRightLeft, FileText, Undo, Coffee, Smartphone, 
  Gamepad2, Music, Camera, Heart, Star, ShoppingCart, Landmark, 
  CreditCard, Banknote, Receipt, PiggyBank, GraduationCap, Stethoscope,
  PlaneTakeoff, Bus, Bike, Fuel, Lightbulb, Tv, Wifi, Phone, 
  Dumbbell, Scissors, Shirt, Baby, Dog, Cat, TreePine, Cloud, 
  Sun, Moon, Umbrella, Map, Globe, Flag, Bell, Mail, Lock, 
  Key, User, Users, Search, HelpCircle, Info
} from 'lucide-react';

export const ICON_OPTIONS = [
  { name: 'Tag', icon: Tag },
  { name: 'Wallet', icon: Wallet },
  { name: 'TrendingUp', icon: TrendingUp },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'BarChart', icon: BarChart },
  { name: 'Home', icon: Home },
  { name: 'Gift', icon: Gift },
  { name: 'Utensils', icon: Utensils },
  { name: 'Car', icon: Car },
  { name: 'ShoppingBag', icon: ShoppingBag },
  { name: 'Film', icon: Film },
  { name: 'HeartPulse', icon: HeartPulse },
  { name: 'Zap', icon: Zap },
  { name: 'Book', icon: Book },
  { name: 'Plane', icon: Plane },
  { name: 'Shield', icon: Shield },
  { name: 'Settings', icon: Settings },
  { name: 'RefreshCw', icon: RefreshCw },
  { name: 'ArrowRightLeft', icon: ArrowRightLeft },
  { name: 'FileText', icon: FileText },
  { name: 'Undo', icon: Undo },
  { name: 'Coffee', icon: Coffee },
  { name: 'Smartphone', icon: Smartphone },
  { name: 'Gamepad2', icon: Gamepad2 },
  { name: 'Music', icon: Music },
  { name: 'Camera', icon: Camera },
  { name: 'Heart', icon: Heart },
  { name: 'Star', icon: Star },
  { name: 'ShoppingCart', icon: ShoppingCart },
  { name: 'Landmark', icon: Landmark },
  { name: 'CreditCard', icon: CreditCard },
  { name: 'Banknote', icon: Banknote },
  { name: 'Receipt', icon: Receipt },
  { name: 'PiggyBank', icon: PiggyBank },
  { name: 'GraduationCap', icon: GraduationCap },
  { name: 'Stethoscope', icon: Stethoscope },
  { name: 'PlaneTakeoff', icon: PlaneTakeoff },
  { name: 'Bus', icon: Bus },
  { name: 'Bike', icon: Bike },
  { name: 'Fuel', icon: Fuel },
  { name: 'Lightbulb', icon: Lightbulb },
  { name: 'Tv', icon: Tv },
  { name: 'Wifi', icon: Wifi },
  { name: 'Phone', icon: Phone },
  { name: 'Dumbbell', icon: Dumbbell },
  { name: 'Scissors', icon: Scissors },
  { name: 'Shirt', icon: Shirt },
  { name: 'Baby', icon: Baby },
  { name: 'Dog', icon: Dog },
  { name: 'Cat', icon: Cat },
  { name: 'TreePine', icon: TreePine },
  { name: 'Cloud', icon: Cloud },
  { name: 'Sun', icon: Sun },
  { name: 'Moon', icon: Moon },
  { name: 'Umbrella', icon: Umbrella },
  { name: 'Map', icon: Map },
  { name: 'Globe', icon: Globe },
  { name: 'Flag', icon: Flag },
  { name: 'Bell', icon: Bell },
  { name: 'Mail', icon: Mail },
  { name: 'Lock', icon: Lock },
  { name: 'Key', icon: Key },
  { name: 'User', icon: User },
  { name: 'Users', icon: Users },
  { name: 'Search', icon: Search },
  { name: 'HelpCircle', icon: HelpCircle },
  { name: 'Info', icon: Info },
];

export const IconRenderer = ({ name, className }: { name?: string, className?: string }) => {
  const iconObj = ICON_OPTIONS.find(i => i.name === name);
  if (!iconObj) return <Tag className={className} />;
  const IconComponent = iconObj.icon;
  return <IconComponent className={className} />;
};
